### ISSUE TITLE
The autoexec.bas stays loaded after timeout error

### ISSUE THREAD

**Issue by Galbi3000** [Threetwosevensixseven/nxtp#1]
I just installed the RTC and WiFi module into my Spectrum Next today and followed a video tutorial to set up automatic time setting using autoexec.bas, they used your same example.
Now every time I boot up or issue the NEW command the autoexec.bas file is left loaded in memory.

If I run the program manually I get an error: `F WiFi/server timeout, 10:1`
I assume this is why the file stays loaded in memory?

The WiFi is correctly set up, running the WIFI2.BAS file shows the connection details fine after rebooting. Is there a problem with the server or is the timeout too short to allow for internet congestion?

**Comment by Galbi3000** [comment]
I'm still learning the Next features as I have only had my machine a few days.
I just looked up in the fine manual the autoexec.bas proper use and it seems you have missed an important command!

If you replace `20 GO TO 1000` with `20 ERASE` then the program should work properly and erase itself after a successful time update.

This of course does not get run if the timeout occurs so I am still left with the autoexec.bas loaded in memory.

**Comment by Threetwosevensixseven** [comment]
Hi, apologies that I didn't reply before.

The intention was to return real ZX BASIC errors, and for people to use `ON ERROR` handling to handle them (for example to retry one more time, as one user wanted to be able to do).

If you wanted to ignore the error you could do something like this:

```
 10 ON ERROR GO TO 30
 20 .nxtp time.nxtel.org 12300
 30 ON ERROR
 40 ERASE
999 SAVE "c:/NextZXOS/autoexec.bas" LINE 0
```

I upated the wiki page with this example. Hopefully this does what you need.

**Comment by Galbi3000** [comment]
Hehe, almost 3 years. 😛
Thanks for the update though. 🙂
