### ISSUE TITLE
NXTP Public Server

### ISSUE THREAD

**Issue by syroegkin** [Threetwosevensixseven/nxtp#2]
Hi,

I wanted to inform you that I have developed the Node.js implementation of the [nxtp server](https://github.com/syroegkin/nxtp-js). Additionally, I have set up a new public server that runs the Node.js nxtp server, which can be accessed at time.zx.in.net:12300.

I kindly request you to consider adding this server address to the list of public servers.

Thank you in advance.

**Comment by Threetwosevensixseven** [comment]
Thank you Sergii!

I've added your server address, as well as a few links to your project.

Many thanks for collaborating :)

**Comment by syroegkin** [comment]
Thank you Robin!
